[package]
name = "uu"
version = "1.0.0"
authors = ["Pablo Tato Ramos"]
license = "MIT"
edition = "2018"

[dependencies.sdl2]
git = "https://github.com/Rust-SDL2/rust-sdl2.git"
default-features = false
features = [ "bundled", "ttf" ]

[dependencies.linked-list]
git = "https://github.com/contain-rs/linked-list"
